logging:
  file:
    path: ./log
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/k8s?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: UTF-8
mybatis:
  mapper-locations: classpath:user/*.xml